# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

FROM amazonlinux:2.0.20200602.0
RUN yum update -y
RUN yum install -y python3-pip zip 
RUN yum -y clean all
